WebDienThoaiDiDong/WebDienThoaiDiDong/Models/CHI_TIET_SAN_PHAM.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDienThoaiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_SAN_PHAM
    {
        public int MaCTSP { get; set; }
        public Nullable<int> MaSanPham { get; set; }
        public string Mau { get; set; }
        public Nullable<int> Gia { get; set; }
        public Nullable<bool> Isdeleted { get; set; }
    
        public virtual SAN_PHAM SAN_PHAM { get; set; }
    }
}

WebDienThoaiDiDong/WebDienThoaiDiDong/Controllers/ChiTietSanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebDienThoaiDiDong.Models;
namespace WebDienThoaiDiDong.Controllers
{
    public class ChiTietSanPhamController : Controller
    {
        QuanLyBanDienThoaiEntities db = new QuanLyBanDienThoaiEntities();
        
        // GET: ChiTietSanPham
        public ActionResult Index(string tensanpham, int id)
        {
            ViewBag.lstSlidesanpham = db.ANH_SAN_PHAM.Where(n =>n.IsDeleted == false && n.MaSanPham == id).OrderByDescending(n => n.MaAnhSanPham).Take(4).ToList();
            var model = db.SAN_PHAM.FirstOrDefault(n => n.MaSanPham == id && n.IsDeleted == false);
            ViewBag.Tintucsanpham = db.TIN_TUC_SAN_PHAM.Where(n => n.MaSanPham == id && n.IsDeleted == false).ToList();
            ViewBag.lstSanphamlienquan = db.SAN_PHAM.Where(n => n.MaCTDM == model.MaCTDM && n.IsDeleted == false).ToList();
            
            TempData["Gia"] = model.GiaSanPham;
           return View(model);
        }
        public ActionResult SearchMau(string codesearch,int id)
         {
            var result = db.SAN_PHAM.FirstOrDefault(n => n.MaSanPham == id);
            
            
            if(codesearch == "")
            {
                ViewBag.Mau = "Mặc định";
                ViewBag.Gia = result.GiaSanPham;
                ViewBag.activegroup = "";
            }
            else
            {
                ViewBag.Gia = db.CHI_TIET_SAN_PHAM.FirstOrDefault(n => n.Mau.Contains(codesearch)).Gia;
                ViewBag.Mau = db.CHI_TIET_SAN_PHAM.FirstOrDefault(n => n.Mau.Contains(codesearch)).Mau;
                ViewBag.activegroup = codesearch;
            }
            ViewBag.group = db.CHI_TIET_SAN_PHAM.Where(n => n.MaSanPham == id).ToList();
            return View(result);
        }
    }
}

WebDienThoaiDiDong/WebDienThoaiDiDong/Controllers/TrangChuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebDienThoaiDiDong.Models;

namespace WebDienThoaiDiDong.Controllers
{
    public class TrangChuController : Controller
    {
        QuanLyBanDienThoaiEntities db = new QuanLyBanDienThoaiEntities();
        private const string CartSession = "CartSession";
        public ActionResult Index()
        {
            ViewBag.lstSlide = db.SLIDE_TRANG_CHU.Where(n => n.IsDeleted == false).OrderByDescending(n => n.Id).Take(4).ToList();
            ViewBag.lstTincongnghe = db.TIN_TUC.Where(n => n.IsDeleted == false).OrderBy(n => n.NgayTao).Take(3).ToList();
            ViewBag.lstSanphammoi = db.SAN_PHAM.Where(n => n.IsDeleted == false && (n.CHI_TIET_DANH_MUC.MaDanhMuc == 1 || n.CHI_TIET_DANH_MUC.MaDanhMuc == 2)).OrderBy(n => n.NgayTao).Take(3).ToList();
            ViewBag.lstSanphamtieubieu = db.SAN_PHAM.Where(n => n.IsDeleted == false && (n.CHI_TIET_DANH_MUC.MaDanhMuc == 1 || n.CHI_TIET_DANH_MUC.MaDanhMuc == 2)).OrderByDescending(n => n.GiaSanPham).Take(12).ToList();
            ViewBag.lstPhukien = db.SAN_PHAM.Where(n => n.IsDeleted == false && n.CHI_TIET_DANH_MUC.MaDanhMuc == 3).OrderBy(n => n.NgayTao).Take(4).ToList();
            return View();
        }
        public ActionResult DangXuat()
        {
            Session["TenDangNhap"] = null;
            return RedirectToAction("Index");
        }
        public ActionResult Menu()
        {
            ViewBag.count1 = db.CHI_TIET_DANH_MUC.Count(n => n.IsDeleted == false && n.MaDanhMuc == 1);
            ViewBag.count2 = db.CHI_TIET_DANH_MUC.Count(n => n.IsDeleted == false && n.MaDanhMuc == 2);
            ViewBag.count3 = db.CHI_TIET_DANH_MUC.Count(n => n.IsDeleted == false && n.MaDanhMuc == 3);
            ViewBag.lst2 = db.CHI_TIET_DANH_MUC.Where(n => n.IsDeleted == false && n.MaDanhMuc == 2).ToList();
            ViewBag.lst3 = db.CHI_TIET_DANH_MUC.Where(n => n.IsDeleted == false && n.MaDanhMuc == 3).ToList();

            var result = db.CHI_TIET_DANH_MUC.Where(n => n.IsDeleted == false).OrderBy(n => n.MaDanhMuc).ToList();
            return View(result);
        }
        public PartialViewResult HeaderCart()
        {
            var cart = Session[CartSession];
            var list = new List<CartItem>();
            if (cart != null)
            {
                list = (List<CartItem>)cart;
            }
            return PartialView(list);
        }
    }
}

WebDienThoaiDiDong/WebDienThoaiDiDong/Views/ChiTietSanPham/Index.cshtml
@using WebDienThoaiDiDong.Models;
@model SAN_PHAM
@{
    ViewBag.Title = Model.TenSanPham;
    int id = Model.MaSanPham;
}
<div id="fb-root"></div>
<script>
(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.9";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<script>
    var gia = 0;
</script>
<link href="~/Content/css/chitietsanpham.css" rel="stylesheet" />
<div class="container" style="margin-top:10px">
    <!-- Page Content -->
    <div class="row">
        <div class="breadcrumb" style="margin-bottom: 20px;">
            <span itemscope="itemscope" class="crumb_item">
                <a itemprop="url" rel="up" class="crumb" href="@Url.Action("Index","TrangChu")"><span itemprop="title">Trang chủ</span></a>
                <span class="arrow"> » </span>
            </span>
            <span itemscope="itemscope" class="crumb_item">
                <a itemprop="url" rel="up" class="crumb" href="@Url.Action("Index","DienThoaiDiDong")"><span itemprop="title">Điện thoại di động</span></a>
                <span class="arrow"> » </span>
            </span>
            <span itemscope="itemscope" class="crumb_item">
                <a itemprop="url" rel="up" class="crumb" href="@Url.Action("Index","ChiTietSanPham",new { @TenSanPham = Model.TenSanPham,@id = Model.MaSanPham})"><span itemprop="title">@Model.TenSanPham</span></a>
            </span>
        </div>

        <!--slider-->
        <div class="col-md-7">
            <p style="font-size:22px; font-weight: bold;">@Model.TieuDeSanPham</p>
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                    <li data-target="#myCarousel" data-slide-to="3"></li>
                </ol>

                <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox">
                    @{ int count = 0;}
                    @foreach (var item in (List<ANH_SAN_PHAM>)ViewBag.lstSlidesanpham)
                    {
                        count++;
                        if (count == 1)
                        {
                            <div class="item active">
                                <img class="img-slider" src="~/Images/ImagesSliderProduct/@item.AnhMinhHoa" alt="noel" >
                            </div>
                        }
                        else
                        {
                            <div class="item">
                                <img class="img-slider" src="~/Images/ImagesSliderProduct/@item.AnhMinhHoa" alt="Chania" >
                            </div>
                        }
                    }
                    

                   

                </div>

                <!-- Left and right controls -->
                <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev" style="background: none;">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next" style="background: none;">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
        <div class="col-md-5">
            @if (Model.SoLuongTrongKho == 0)
            {
                <p style="font-size:14px; font-weight: bold;margin-top:2.5em;color: red;">HẾT HÀNG</p>
            }
            else
            {
                <p style="font-size:14px; font-weight: bold;margin-top:2.5em;    color: #008aca">CÒN HÀNG</p>
            }
            <div id="divsearchmau">
                
            </div>
            
</div>
        
        <!- 	-cấu hình chi tiết-->
        <div class="col-md-7 " id="ch">
            <div class="col-md-6" class="m">
                <img class="sp" src="~/Images/ImagesSliderProduct/@Model.AnhDaiDien">
            </div>
            <div class="col-md-6">
                <p><span class="cauhinh">Màn hình: </span> <span>@Model.ManHinh</span></p>
                <p><span class="cauhinh">CPU: </span><span>@Model.Cpu</span></p>
                <p><span class="cauhinh">Ram: </span> <span>@Model.Ram</span></p>
                <p><span class="cauhinh">Hệ điều hành: </span><span>@Model.HeDieuHanh</span></p>
                <p><span class="cauhinh">Camera chính:  </span><span>@Model.CameraChinh</span></p>
                <p><span class="cauhinh">Camera phụ:  </span><span>@Model.CameraPhu</span></p>
                <p><span class="cauhinh">Bộ nhớ trong:  </span><span> @Model.BoNhoTrong</span></p>
                <p><span class="cauhinh">Thẻ nhớ ngoài:  </span><span>@Model.TheNhoNgoai</span></p>
                <p><span class="cauhinh">Dung lượng pin:  </span><span> @Model.DungLuongPin</span></p>

            </div>
            <div class="video col-md-12">
                @Html.Raw(Model.Video)
            </div>
            <div class="xemchitiet col-md-12">
                <button type="button" class="btn btn-success" data-toggle="collapse" data-target="#chitiet">
                    Đánh giá chi tiết
                </button>
                <div id="chitiet" class="collapse">
                    @foreach (var item in (List<TIN_TUC_SAN_PHAM>)ViewBag.Tintucsanpham)
                    {
                        <img class="img_tintuc" src="~/Images/ImagesProductNews/@item.AnhTinTuc">
                    }
                    
                    <p>
                        @foreach (var item in (List<TIN_TUC_SAN_PHAM>)ViewBag.Tintucsanpham)
                        {
                            @item.NoiDungTinTuc
                        }
                    </p>
                </div>
            </div>
            <div class="col-md-12">
                <div class="fb-comments" data-href="@Request.Url.ToString()" data-width="100%" data-mobile="true" data-numposts="5"></div>
            </div>
        </div>
        <div class="col-md-5" class="divsplienquan">
            <div class="title">
                <p>SẢN PHẨM LIÊN QUAN</p>
            </div>
            @foreach (var item in (List<SAN_PHAM>)ViewBag.lstSanphamlienquan)
            {
                <a href="@Url.Action("Index","ChiTietSanPham",new { @TenSanPham = item.TenSanPham,@id = item.MaSanPham})">
                    <div class="splienquan col-md-6 col-sm-4 col-xs-6">
                        <img class="anhsp" src="~/Images/ImagesSliderProduct/@item.AnhDaiDien">
                        <p style="font-size:17px; font-weight: bold;">@item.TenSanPham</p>
                        <p class="pro_price" data-price="1200000" style="font-size:20px; font-weight: bold;color:red;">@String.Format("{0:0,0}", item.GiaSanPham) ₫</p>
                    </div>
                </a>
            }
            
           
        </div>
    </div>
    <!-- /.row -->
</div>

<script>
    var id = @id;
    $(document).ready(function () {
        $.ajax({
            url: '@Url.Action("SearchMau", "ChiTietSanPham")',
            mtype: "POST",
            datatype: "json",
            data: {
                codesearch: "",
                id:id
            },
            success: function (data) {
                $("#divsearchmau").html(data);
            }
        });
    });





</script>

WebDienThoaiDiDong/WebDienThoaiDiDong/Views/ChiTietSanPham/SearchMau.cshtml
@using WebDienThoaiDiDong.Models;
@model SAN_PHAM
@{
    Layout = null;
    int gia = ViewBag.Gia;
}
<script>
    $('#a #myoption').change(function () {
        var codesearch = $('#myoption option:selected').text().trim();

        $.ajax({
            url: '@Url.Action("SearchMau", "ChiTietSanPham")',
            mtype: "POST",
            datatype: "json",
            data: {
                codesearch: codesearch,
                id: id
            },
            success: function (data) {
                var st = parseInt(@gia);
                $("#txtgia").text(st.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + "đ");
                $("#divsearchmau").html(data);
               
            }
        });
    });
</script>
<p class="pro_price" data-price="1200000" style="font-size:24px; font-weight: bold;color:red;" id="txtgia">@String.Format("{0:0,0}", ViewBag.Gia) ₫</p>
<p><span style="font-size:13px; font-weight: bold;">Bảo hành: </span><span>@Model.CheDoBaoHanh</span></p>
<div id="a">
    <span style="font-size:13px; font-weight: bold;">
        Màu sắc:
    </span>
    <select class="prodetail_rom_select" id="myoption">
        @foreach (var item in (List<CHI_TIET_SAN_PHAM>)ViewBag.group)
        {
            if (ViewBag.activegroup == "")
            {
                <option>@item.Mau</option>
            }
            else
            {
                if (item.Mau == ViewBag.activegroup)
                {
                    <option selected>@item.Mau</option>
                }
                else
                {
                    <option>@item.Mau</option>
                }
            }
        }


    </select>
</div>
<div class="khuyenmai">
    <div class="khuyenmai-trong">
        @Html.Raw(Model.KhuyenMai)
    </div>
</div>
<div class="v2_prodetail_action">
    @*<a class="pro_shop_action" id="muahangonline" href="#">MUA HÀNG ONLINE</a>*@
    <a class="pro_shop_action"  href="/GioHang/AddItem?masanpham=@Model.MaSanPham&quantity=1&giasanpham=@ViewBag.Gia&mausac=@ViewBag.Mau">MUA HÀNG ONLINE</a>
    
</div>