WebDienThoaiDiDong/WebDienThoaiDiDong/Controllers/MayTinhBangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebDienThoaiDiDong.Models;

namespace WebDienThoaiDiDong.Controllers
{
    public class MayTinhBangController : Controller
    {
        QuanLyBanDienThoaiEntities db = new QuanLyBanDienThoaiEntities();
        // GET: MayTinhBang
        public ActionResult Index(string tenhang = "", int count = 0)
        {
            ViewBag.lstHangsanxuat = db.CHI_TIET_DANH_MUC.Where(n => n.IsDeleted == false && n.MaDanhMuc == 2).OrderBy(n => n.NgayTao).ToList();
            if (tenhang != "")
            {
                count = count + 4;
                TempData["lstMayTinhBang"] = db.SAN_PHAM.Where(n => n.CHI_TIET_DANH_MUC.MaDanhMuc == 2 && n.IsDeleted == false && n.CHI_TIET_DANH_MUC.TenHang.Contains(tenhang)).OrderBy(n => n.NgayTao).Take(count).ToList();
                var a = db.SAN_PHAM.Where(n => n.CHI_TIET_DANH_MUC.MaDanhMuc == 2 && n.IsDeleted == false && n.CHI_TIET_DANH_MUC.TenHang.Contains(tenhang)).OrderBy(n => n.NgayTao).ToList();
                TempData["countSpconlai"] = a.Skip(count).Count();
            }
            return View();
        }
        public ActionResult MayTinhBang(int count)
        {
            count = count + 4;
            ViewBag.lstMayTinhBang = db.SAN_PHAM.Where(n => n.CHI_TIET_DANH_MUC.MaDanhMuc == 2 && n.IsDeleted == false).OrderBy(n => n.NgayTao).Take(count).ToList();
            var a = db.SAN_PHAM.Where(n => n.CHI_TIET_DANH_MUC.MaDanhMuc == 2 && n.IsDeleted == false).OrderBy(n => n.NgayTao).ToList();
            ViewBag.countSpconlai = a.Skip(count).Count();
            if (TempData["lstMayTinhBang"] != null)
            {
                ViewBag.lstMayTinhBang = TempData["lstMayTinhBang"];
                ViewBag.countSpconlai = TempData["countSpconlai"];
            }
            return View();
        }
        public ActionResult Search(string codesearch1, string codesearch2, string codesearch3, int count)
        {
            var Tenhang = db.CHI_TIET_DANH_MUC.FirstOrDefault(n => n.TenHang == codesearch2);
            count = count + 4;
            switch (codesearch1)
            {
                case "Dưới 1 triệu":
                    {
                        ViewBag.lstMayTinhBang = db.SAN_PHAM.Where(n => n.CHI_TIET_DANH_MUC.MaDanhMuc == 2 && n.IsDeleted == false && n.GiaSanPham <= 1000000).OrderBy(n => n.NgayTao).Take(count).ToList();
                        var a = db.SAN_PHAM.Where(n => n.CHI_TIET_DANH_MUC.MaDanhMuc == 2 && n.IsDeleted == false && n.GiaSanPham <= 1000000).OrderBy(n => n.NgayTao).ToList();
                        ViewBag.countSpconlai = a.Skip(count).Count();
                        break;
                    }
                case "Dưới 2 triệu":
                    {
                        ViewBag.lstMayTinhBang = db.SAN_PHAM.Where(n => n.CHI_TIET_DANH_MUC.MaDanhMuc == 2 && n.IsDeleted == false && n.GiaSanPham <= 2000000).OrderBy(n => n.NgayTao).Take(count).ToList();
                        var a = db.SAN_PHAM.Where(n => n.CHI_TIET_DANH_MUC.MaDanhMuc == 2 && n.IsDeleted == false && n.GiaSanPham <= 2000000).OrderBy(n => n.NgayTao).ToList();
                        ViewBag.countSpconlai = a.Skip(count).Count();
                        break;
                    }
                case "Dưới 3 triệu":
                    {
                        ViewBag.lstMayTinhBang = db.SAN_PHAM.Where(n => n.CHI_TIET_DANH_MUC.MaDanhMuc == 2 && n.IsDeleted == false && n.GiaSanPham <= 3000000).OrderBy(n => n.NgayTao).Take(count).ToList();
                        var a = db.SAN_PHAM.Where(n => n.CHI_TIET_DANH_MUC.MaDanhMuc == 2 && n.IsDeleted == false && n.GiaSanPham <= 3000000).OrderBy(n => n.NgayTao).ToList();
                        ViewBag.countSpconlai = a.Skip(count).Count();
                        break;
                    }
                case "Dưới 5 triệu":
                    {
                        ViewBag.lstMayTinhBang = db.SAN_PHAM.Where(n => n.CHI_TIET_DANH_MUC.MaDanhMuc == 2 && n.IsDeleted == false && n.GiaSanPham <= 5000000).OrderBy(n => n.NgayTao).Take(count).ToList();
                        var a = db.SAN_PHAM.Where(n => n.CHI_TIET_DANH_MUC.MaDanhMuc == 2 && n.IsDeleted == false && n.GiaSanPham <= 5000000).OrderBy(n => n.NgayTao).ToList();
                        ViewBag.countSpconlai = a.Skip(count).Count();
                        break;
                    }
                case "Dưới 8 triệu":
                    {
                        ViewBag.lstMayTinhBang = db.SAN_PHAM.Where(n => n.CHI_TIET_DANH_MUC.MaDanhMuc == 2 && n.IsDeleted == false && n.GiaSanPham <= 8000000).OrderBy(n => n.NgayTao).Take(count).ToList();
                        var a = db.SAN_PHAM.Where(n => n.CHI_TIET_DANH_MUC.MaDanhMuc == 2 && n.IsDeleted == false && n.GiaSanPham <= 8000000).OrderBy(n => n.NgayTao).ToList();
                        ViewBag.countSpconlai = a.Skip(count).Count();
                        break;
                    }
                case "Dưới 10 triệu":
                    {
                        ViewBag.lstMayTinhBang = db.SAN_PHAM.Where(n => n.CHI_TIET_DANH_MUC.MaDanhMuc == 2 && n.IsDeleted == false && n.GiaSanPham <= 10000000).OrderBy(n => n.NgayTao).Take(count).ToList();
                        var a = db.SAN_PHAM.Where(n => n.CHI_TIET_DANH_MUC.MaDanhMuc == 2 && n.IsDeleted == false && n.GiaSanPham <= 10000000).OrderBy(n => n.NgayTao).ToList();
                        ViewBag.countSpconlai = a.Skip(count).Count();
                        break;
                    }
                case "Trên 10 triệu":
                    {
                        ViewBag.lstMayTinhBang = db.SAN_PHAM.Where(n => n.CHI_TIET_DANH_MUC.MaDanhMuc == 2 && n.IsDeleted == false && n.GiaSanPham >= 10000000).OrderBy(n => n.NgayTao).Take(count).ToList();
                        var a = db.SAN_PHAM.Where(n => n.CHI_TIET_DANH_MUC.MaDanhMuc == 2 && n.IsDeleted == false && n.GiaSanPham >= 10000000).OrderBy(n => n.NgayTao).ToList();
                        ViewBag.countSpconlai = a.Skip(count).Count();
                        break;
                    }


            }
            if (Tenhang != null && codesearch2 == Tenhang.TenHang)
            {
                if (codesearch3 == "")
                {
                    ViewBag.lstMayTinhBang = db.SAN_PHAM.Where(n => n.CHI_TIET_DANH_MUC.MaDanhMuc == 2 && n.IsDeleted == false && n.CHI_TIET_DANH_MUC.TenHang.Contains(Tenhang.TenHang)).OrderBy(n => n.NgayTao).Take(count).ToList();
                    var a = db.SAN_PHAM.Where(n => n.CHI_TIET_DANH_MUC.MaDanhMuc == 2 && n.IsDeleted == false && n.CHI_TIET_DANH_MUC.TenHang.Contains(Tenhang.TenHang)).OrderBy(n => n.NgayTao).ToList();
                    ViewBag.countSpconlai = a.Skip(count).Count();
                }
                else
                {
                    if (codesearch3 == "Giá giảm dần")
                    {
                        ViewBag.lstMayTinhBang = db.SAN_PHAM.Where(n => n.CHI_TIET_DANH_MUC.MaDanhMuc == 2 && n.IsDeleted == false && n.CHI_TIET_DANH_MUC.TenHang.Contains(Tenhang.TenHang)).OrderByDescending(n => n.GiaSanPham).Take(count).ToList();
                        var a = db.SAN_PHAM.Where(n => n.CHI_TIET_DANH_MUC.MaDanhMuc == 2 && n.IsDeleted == false && n.CHI_TIET_DANH_MUC.TenHang.Contains(Tenhang.TenHang)).OrderByDescending(n => n.GiaSanPham).ToList();
                        ViewBag.countSpconlai = a.Skip(count).Count();
                    }
                    else
                    {
                        ViewBag.lstMayTinhBang = db.SAN_PHAM.Where(n => n.CHI_TIET_DANH_MUC.MaDanhMuc == 2 && n.IsDeleted == false && n.CHI_TIET_DANH_MUC.TenHang.Contains(Tenhang.TenHang)).OrderBy(n => n.GiaSanPham).Take(count).ToList();
                        var a = db.SAN_PHAM.Where(n => n.CHI_TIET_DANH_MUC.MaDanhMuc == 2 && n.IsDeleted == false && n.CHI_TIET_DANH_MUC.TenHang.Contains(Tenhang.TenHang)).OrderBy(n => n.GiaSanPham).ToList();
                        ViewBag.countSpconlai = a.Skip(count).Count();
                    }

                }

            }

            if (Tenhang != null && codesearch2 == Tenhang.TenHang && codesearch1 != "")
            {
                switch (codesearch1)
                {
                    case "Dưới 1 triệu":
                        {
                            ViewBag.lstMayTinhBang = db.SAN_PHAM.Where(n => n.CHI_TIET_DANH_MUC.MaDanhMuc == 2 && n.IsDeleted == false && n.GiaSanPham <= 1000000 && n.CHI_TIET_DANH_MUC.TenHang.Contains(Tenhang.TenHang)).OrderBy(n => n.NgayTao).Take(count).ToList();
                            var a = db.SAN_PHAM.Where(n => n.CHI_TIET_DANH_MUC.MaDanhMuc == 2 && n.IsDeleted == false && n.GiaSanPham <= 1000000 && n.CHI_TIET_DANH_MUC.TenHang.Contains(Tenhang.TenHang)).OrderBy(n => n.NgayTao).ToList();
                            ViewBag.countSpconlai = a.Skip(count).Count();
                            break;
                        }
                    case "Dưới 2 triệu":
                        {
                            ViewBag.lstMayTinhBang = db.SAN_PHAM.Where(n => n.CHI_TIET_DANH_MUC.MaDanhMuc == 2 && n.IsDeleted == false && n.GiaSanPham <= 2000000 && n.CHI_TIET_DANH_MUC.TenHang.Contains(Tenhang.TenHang)).OrderBy(n => n.NgayTao).Take(count).ToList();
                            var a = db.SAN_PHAM.Where(n => n.CHI_TIET_DANH_MUC.MaDanhMuc == 2 && n.IsDeleted == false && n.GiaSanPham <= 2000000 && n.CHI_TIET_DANH_MUC.TenHang.Contains(Tenhang.TenHang)).OrderBy(n => n.NgayTao).ToList();
                            ViewBag.countSpconlai = a.Skip(count).Count();
                            break;
                        }
                    case "Dưới 3 triệu":
                        {

WebDienThoaiDiDong/WebDienThoaiDiDong/Views/MayTinhBang/Index.cshtml
@using WebDienThoaiDiDong.Models;
@{
    ViewBag.Title = "Máy tính bảng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class=" row">
        <div class="breadcrumb" style="margin-bottom: 20px;">
            <span itemscope="itemscope" class="crumb_item">
                <a itemprop="url" rel="up" class="crumb" href="@Url.Action("Index","TrangChu")"><span itemprop="title">Trang chủ</span></a>
                <span class="arrow"> » </span>
            </span>
            <span itemscope="itemscope" class="crumb_item">
                <a itemprop="url" rel="up" class="crumb" href="@Url.Action("Index","MayTinhBang")"><span itemprop="title">Máy tính bảng</span></a>
                <span class="arrow"> » </span>
            </span>
            <span itemscope="itemscope" class="crumb_item">
                <a itemprop="url" rel="up" class="crumb" href=""><span itemprop="title"></span></a>
            </span>
        </div>
    </div>

    <div class="title-dtdd2 row">
        <div class="col-md-12 col-sm-12 col-xs-12" style="margin-bottom:0.5em;">
            <span itemscope="itemscope" class="crumb_item">
                <span itemprop="title">Tìm theo</span>
                <span class="arrow"> » </span>
            </span>
            <div class="btn-group">
                <button id="btn-mucgia" class="btn btn-info">Mức giá</button>
                <button data-toggle="dropdown" class="btn btn-info dropdown-toggle"><span class="caret"></span></button>
                <ul id="mucgia" class="dropdown-menu">
                    <li><a href="#">Dưới 1 triệu</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Dưới 2 triệu</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Dưới 3 triệu</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Dưới 5 triệu</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Dưới 8 triệu</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Dưới 10 triệu</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Trên 10 triệu</a></li>
                </ul>
            </div>
            <div class="btn-group">
                <button id="btn-hangsanxuat" class="btn btn-info">Hãng sản xuất</button>
                <button data-toggle="dropdown" class="btn btn-info dropdown-toggle"><span class="caret"></span></button>
                <ul id="hangsanxuat" class="dropdown-menu">
                    @foreach (var item in (List<CHI_TIET_DANH_MUC>)ViewBag.lstHangsanxuat)
                    {
                        <li><a href="#">@item.TenHang</a></li>
                        <li class="divider"></li>
                    }


                </ul>
            </div>
            <div class="btn-group">
                <button id="btn-timtatca" class="btn btn-info" onclick="timtatca()">Tìm tất cả</button>
            </div>
            <div class="btn-group" style="float:right;">
                <button id="btn-sapxep" class="btn btn-info">Sắp xếp hiển thị theo</button>
                <button data-toggle="dropdown" class="btn btn-info dropdown-toggle"><span class="caret"></span></button>
                <ul id="sapxep" class="dropdown-menu">
                    <li><a href="#">Giá giảm dần</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Giá tăng dần</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="title row">
        <div class="title-sanphamtieubieu col-md-12 col-sm-12 col-xs-12">
            <a href="">MÁY TÍNH BẢNG</a>
        </div>
    </div>

    <div id="divMaytinhbang">

    </div>

</div>
<script>
        var checksearch = 0;
        var codesearch1 = "";
        var codesearch2 = "";
        var codesearch3 = "";
        var dem = 0;
        $(document).ready( function(){
            $.ajax({
                url: '@Url.Action("MayTinhBang", "MayTinhBang")',
                mtype: "POST",
                datatype: "json",
                data:{
                    count:0
                },
                success: function (data) {
                    $("#divMaytinhbang").html(data);
                }
            });
        });
        function xemthem(count) {
            dem = count;
            if (checksearch == 0) {
                $.ajax({
                    url: '@Url.Action("MayTinhBang", "MayTinhBang")',
                    mtype: "POST",
                    datatype: "json",
                    data: {
                        count: dem
                    },
                    success: function (data) {
                        $("#divMaytinhbang").html(data);
                    }
                });
            } else {
                $.ajax({
                    url: '@Url.Action("Search", "MayTinhBang")',
                    mtype: "POST",
                    datatype: "json",
                    data: {
                        codesearch1: codesearch1,
                        codesearch2: codesearch2,
                        codesearch3: codesearch3,
                        count: dem
                    },
                    success: function (data) {
                        $("#divMaytinhbang").html(data);
                    }
                });

            }

        }
        $(function () {
            $("#mucgia li a").click(function () {
                codesearch3 = "";
                $("#btn-sapxep").text("Sắp xếp theo");
                $("#btn-sapxep").val("");
                checksearch = 1;
                $("#btn-mucgia").text($(this).text());
                codesearch1 = $(this).text();
                $.ajax({
                    url: '@Url.Action("Search", "MayTinhBang")',
                    mtype: "POST",
                    datatype: "json",
                    data: {
                        codesearch1: codesearch1,
                        codesearch2:codesearch2,
                        codesearch3: codesearch3,
                        count:dem
                    },
                    success: function (data) {
                        $("#divMaytinhbang").html(data);
                        dem = 0;
                    }
                });
            });

        });
        $(function () {

            $("#hangsanxuat li a").click(function () {
                checksearch = 1;
                $("#btn-hangsanxuat").text($(this).text());
                codesearch2 = $(this).text();
                $.ajax({
                    url: '@Url.Action("Search", "MayTinhBang")',
                    mtype: "POST",
                    datatype: "json",
                    data: {
                        codesearch1: codesearch1,
                        codesearch2:codesearch2,
                        codesearch3: codesearch3,
                        count: dem
                    },
                    success: function (data) {
                        $("#divMaytinhbang").html(data);
                    }
                });
            });

        });
        $(function () {
            $("#sapxep li a").click(function () {
                codesearch1 = "";
                $("#btn-mucgia").text("Mức giá");
                $("#btn-mucgia").val("");
                checksearch = 1;
                $("#btn-sapxep").text($(this).text());
                codesearch3 = $(this).text();
                $.ajax({
                    url: '@Url.Action("Search", "MayTinhBang")',
                    mtype: "POST",
                    datatype: "json",
                    data: {
                        codesearch1: codesearch1,
                        codesearch2: codesearch2,
                        codesearch3: codesearch3,
                        count: dem
                    },
                    success: function (data) {
                        $("#divMaytinhbang").html(data);
                        dem = 0;
                    }
                });
            });

        });
        function timtatca() {
            checksearch = 0;
            codesearch1 = "";
            codesearch2 = "";
            codesearch3 = "";
            dem = 0;
            $("#btn-mucgia").text("Mức giá");
            $("#btn-mucgia").val("");
            $("#btn-hangsanxuat").text("Hãng sản xuất");
            $("#btn-hangsanxuat").val("");
            $("#btn-sapxep").text("Sắp xếp theo");
            $("#btn-sapxep").val("");
            $.ajax({
                url: '@Url.Action("MayTinhBang", "MayTinhBang")',
                mtype: "POST",
                datatype: "json",
                data: {
                    count: 0
                },
                success: function (data) {
                    $("#divMaytinhbang").html(data);
                }
            });
        }
</script>

WebDienThoaiDiDong/WebDienThoaiDiDong/Views/MayTinhBang/MayTinhBang.cshtml
@using WebDienThoaiDiDong.Models;
@{
    Layout = null;
}
<div class="row">
    @{ int count = 0;}
    @foreach (var item in (List<SAN_PHAM>)ViewBag.lstMayTinhBang)
    {
        count++;
    <div class="sanphamtieubieu col-md-2 col-sm-3 col-xs-6">
        <div class="main">
            <div class="view_dienthoai view-first">
                <a href="@Url.Action("Index","ChiTietSanPham",new { @tensanpham = item.TenSanPham,@id=item.MaSanPham})">
                    <div class="sanphamtieubieu-trong">
                        <img class="img-sanphamtieubieu" src="~/Images/ImagesSliderProduct/@item.AnhDaiDien">
                        @if (item.SoLuongTrongKho > 0)
                        {
                            <p class="trangthai">Còn hàng</p>
                        }
                        else
                        {
                            <p class="trangthai" style="color:red;">Hết hàng</p>
                        }
                        <p class="tensanpham">@item.TenSanPham</p>
                        <p class="gia">@String.Format("{0:0,0 đ}", item.GiaSanPham)  </p>
                    </div>

                    <div class="mask">
                        <h2>@item.TenSanPham</h2>
                        <p>Màn hình: @item.ManHinh</p>
                        <p>HĐH: @item.HeDieuHanh</p>
                        <p>CPU: @item.Cpu</p>
                        <p>RAM: @item.Ram ,Thẻ Nhớ: @item.TheNhoNgoai</p>
                        <p>Camera: @item.CameraChinh, Selfie: @item.CameraPhu</p>
                        <p>PIN: @item.DungLuongPin</p>
                        <a href="@Url.Action("Index","ChiTietSanPham",new { @tensanpham = item.TenSanPham,@id=item.MaSanPham})" class="info">Xem chi tiết</a>
                    </div>
                </a>
            </div>
        </div>

    </div>
    }
@if (ViewBag.countSpconlai != 0)
{
    <div class="xemthem row">
        <div class="col-md-12 col-sm-12 col-xs-12" style="margin-top:1em;">
            <a type="button" class="btn btn-default btn-md" onclick="xemthem(@count)">
                <span> Xem thêm @ViewBag.countSpconlai máy tính bảng </span>
                <span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></span>
            </a>
        </div>
    </div>
}

</div>