WebDienThoaiDiDong/WebDienThoaiDiDong/Areas/Admin/Models/Quanlydanhmuc/PagingQuanLyDanhMuc.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebDienThoaiDiDong.Models;

namespace WebDienThoaiDiDong.Areas.Admin.Models.Quanlydanhmuc
{
    public class PagingQuanLyDanhMuc
    {
        public int page { get; set; }
        public int totalpage { get; set; }
        public int record { get; set; }
        public List<DANH_MUC> List { get; set; }
    }
}

WebDienThoaiDiDong/WebDienThoaiDiDong/Areas/Admin/Controllers/QuanLyDanhMucController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebDienThoaiDiDong.Areas.Admin.Models.Quanlydanhmuc;
using WebDienThoaiDiDong.Models;

namespace WebDienThoaiDiDong.Areas.Admin.Controllers
{
    public class QuanLyDanhMucController : Controller
    {
        QuanLyBanDienThoaiEntities db = new QuanLyBanDienThoaiEntities();
        // GET: Admin/QuanLyDanhMuc
        public ActionResult Index()
        {
            if (Session["TenQuanTri"] != null && Session["MaQuanTri"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "DangNhapAdmin");
            }
        }
        public ActionResult DanhSachDanhMucTable(int page)
        {
            int row = 4;
            int count = 0;
            int totalpages = 0;
            count = db.DANH_MUC.Count(n => n.IsDelteted == false);
            if (count > 0)
            {
                totalpages = (int)Math.Ceiling((decimal)count / row);
            }
            else
            {
                totalpages = 0;
            }
            var start = row * (page - 1);

            var result = db.DANH_MUC.Where(n => n.IsDelteted == false).OrderBy(n => n.NgayTao).Skip(start).Take(row).ToList();
            PagingQuanLyDanhMuc model = new PagingQuanLyDanhMuc();
            model.totalpage = totalpages;
            model.record = count;
            model.List = result;
            model.page = page;
            return View(model);
        }
        public ActionResult Edit(int id, int page)
        {
            ViewBag.page = page;
            var sanpham = db.DANH_MUC.FirstOrDefault(n => n.MaDanhMuc == id);
            if (sanpham != null)
            {    
                return View(sanpham);
            }
            else
            {  
                return View(new DANH_MUC());
            }
        }
        public bool Save(DANH_MUC danhmuc)
        {
            var model = db.DANH_MUC.FirstOrDefault(n => n.MaDanhMuc == danhmuc.MaDanhMuc);
            try
            {
                if (model != null)
                {
                    model.TenDanhMuc = danhmuc.TenDanhMuc;
                    model.NgayTao = danhmuc.NgayTao;
                    model.IsDelteted = danhmuc.IsDelteted;
                    db.SaveChanges();
                }
                else
                {
                    DANH_MUC model2 = new DANH_MUC();
                    model2.TenDanhMuc = danhmuc.TenDanhMuc;
                    model2.NgayTao = DateTime.Now;
                    model2.IsDelteted = false;
                    db.DANH_MUC.Add(model2);
                    db.SaveChanges();
                }
                return true;
            }
            catch (Exception)
            {
                return false;
            }
        }
        public bool Delete(int id)
        {
            var model = db.DANH_MUC.FirstOrDefault(n => n.MaDanhMuc == id);
            if (model != null)
            {
                model.IsDelteted = true;
                db.SaveChanges();

                return true;
            }
            else
            {
                return false;
            }
        }
    }
}

WebDienThoaiDiDong/WebDienThoaiDiDong/Areas/Admin/Views/QuanLyDanhMuc/DanhSachDanhMucTable.cshtml
@using WebDienThoaiDiDong.Areas.Admin.Models.Quanlydanhmuc;
@model PagingQuanLyDanhMuc
@{
    Layout = null;
}
<script>
    var actionUrl = {
        urlEdit: '@Url.Action("Edit", "QuanLyDanhMuc")',
        urlDanhsachdanhmuctable: '@Url.Action("DanhSachDanhMucTable", "QuanLyDanhMuc")',
        urlSave: '@Url.Action("Save", "QuanLyDanhMuc")',
        urlDelete: '@Url.Action("Delete", "QuanLyDanhMuc")'
    }
</script>
<script src="~/Areas/Admin/Scripts/QuanLyDanhMuc/ActionCrud.js"></script>
<link href="~/Areas/Admin/Content/css/mypaging.css" rel="stylesheet" />
<div class="widget-content nopadding" id="tb">
    <table class="table table-bordered table-striped table-hover">
        <thead>
            <tr class="success">
                <th style="background:#28B779; color:white;font-size:13px;">Mã danh mục</th>
                <th style="background:#28B779; color:white;font-size:13px;">Tên danh mục</th>
                <th style="background:#28B779; color:white;font-size:13px;">Ngày tạo</th>
                <th style="background:#28B779; color:white;font-size:13px;">Hành động</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.List)
            {
                <tr>
                    <th style="font-size:11px;width:100px;">@item.MaDanhMuc</th>
                    <th style="font-size:11px;">@item.TenDanhMuc</th>
                    <th style="font-size:11px;">@item.NgayTao</th>
                    <th style="width:150px;">
                        <button style="font-size: 12px; margin-top:-3px; border-radius:3px; margin-bottom:3px;border-radius:4px;" type="button" class="btn-xs btn btn-info " onclick="Edit(@item.MaDanhMuc,@Model.page)">Sửa</button>
                        <button style="font-size: 12px; margin-top:-3px; border-radius:3px;margin-bottom:3px;border-radius:4px;" type="button" class="btn btn-danger" onclick="Delete(@item.MaDanhMuc,@Model.page)">Xóa</button>
                    </th>

                </tr>
            }

        </tbody>

    </table>
</div>
@if (Model.totalpage > 1)
{
    <div class="pagination">
        <nav>
            <ul>
                @if (Model.page <= 1)
                {
                    <li><a style="background:#337AB7; color:#fff;cursor:not-allowed;">Previous</a></li>
                }
                else
                {
                    <li><a id="previous" onclick="previous(@Model.page)">Previous</a></li>
                }

                <li><span style="background:#337AB7; color:#fff;">Trang <span style="font-weight:bold;">@Model.page</span>/<span style="font-weight:bold;">@Model.totalpage</span></span></li>
                @if (Model.page >= Model.totalpage)
                {
                    <li><a style="background:#337AB7; color:#fff; width:40px;cursor:not-allowed;">Next</a></li>
                }
                else
                {
                    <li><a id="next" onclick="next(@Model.page)">Next</a></li>
                }

            </ul>
        </nav>
    </div>
}
<!--phần Edit-->
<div class="widget-box" id="div_edit">
</div>

WebDienThoaiDiDong/WebDienThoaiDiDong/Areas/Admin/Views/QuanLyDanhMuc/Edit.cshtml
@using WebDienThoaiDiDong.Models;
@model DANH_MUC
 @{ 
     Layout = null;
 }
<script>
        var urlSave ='@Url.Action("Save","QuanLyGiaoDich")';
        var urlDsgdtable = '@Url.Action("DanhSachGiaoDichTable", "QuanLyGiaoDich")';
    $("#form_edit").validate({
        rules: {
            TenDanhMuc: {
                required: true,
            }
        }, messages:{TenDanhMuc: "*Tên danh mục không được bỏ trống*"}
    });
</script>
<div class="widget-title">
    <span class="icon"> <i class="icon-align-justify"></i> </span>
    <h5>Sửa đổi thông tin danh mục</h5>
</div>
<div class="widget-content nopadding">
    <form id="form_edit" class="form-horizontal">
        <div class="control-group">
            @Html.HiddenFor(n => n.MaDanhMuc)
            @Html.HiddenFor(n => n.NgayTao)
            @Html.HiddenFor(n => n.IsDelteted)
            @Html.Label("Tên danh mục: ", new { @class = "control-label" })
            <div class="controls">
               @Html.TextBoxFor(n => n.TenDanhMuc, new { @class = "span8"})
            </div>
        </div> 
        <div>
            <button style="margin:7px;" type="button" class="btn btn-success" onclick="luu(@ViewBag.page)">Lưu</button>
            <button style="margin:0px 7px;" type="button" class="btn btn-danger" onclick="dong()">Đóng</button>
        </div>

    </form>

</div>
<style>
    .error {
        color: red;
        font-size: 11px;
    }
</style>

WebDienThoaiDiDong/WebDienThoaiDiDong/Areas/Admin/Views/QuanLyDanhMuc/Index.cshtml
@using WebDienThoaiDiDong.Models;

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<script>
    var formUrl = {
        urlDanhsachdanhmuctable: '@Url.Action("DanhSachDanhMucTable", "QuanLyDanhMuc")',
    }

</script>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Areas/Admin/Scripts/QuanLyDanhMuc/Quanlydanhmuc.js"></script>
<div id="content">
    <!--breadcrumbs-->
    <div id="content-header">
        <div id="breadcrumb"> <a href="index.html" title="Đi đến Trang chủ" class="tip-bottom"><i class="icon-home"></i> Trang chủ</a> <a href="index.html" title="Danh mục" class="tip-bottom">Danh mục</a></div>
        <h1>Quản lý danh mục sản phẩm</h1>
    </div>
    <!--End-breadcrumbs-->
    <!--Action boxes-->
    <div class="container-fluid">
        <!--End-Chart-box-->
        <hr />
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon"> <i class="icon-th"></i> </span>
                <h5>Danh sách danh mục</h5>
                <button type="button" class="btn btn-success" style="float:right;margin:4px 5px;" onclick="Them()">Thêm mới</button>
            </div>
            <div id="table">

            </div>
        </div>
    </div>
</div>
<script>
    function Them() {
        $.ajax({
            type: 'get',
            data: {
                id: 0,
                page: 1
            },
            url: '@Url.Action("Edit","QuanLyDanhMuc")',
            success: function (data) {
                $("#div_edit").html(data);
            }
        });
    }
</script>