WebDienThoaiDiDong/WebDienThoaiDiDong/Areas/Admin/Controllers/DangNhapAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebDienThoaiDiDong.Models;

namespace WebDienThoaiDiDong.Areas.Admin.Controllers
{
    public class DangNhapAdminController : Controller
    {
        QuanLyBanDienThoaiEntities db = new QuanLyBanDienThoaiEntities();
        // GET: Admin/DangNhap
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DangNhap(FormCollection f)
        {
            string username = f["name"];
            string password = f["pass"];
            if (ModelState.IsValid)
            {
                ADMIN admin = db.ADMINs.SingleOrDefault(n => n.TenDangNhap == username && n.MatKhau == password);
                if (admin != null)
                {
                    Session["TenQuanTri"] = admin.TenQuanTri;
                    Session["MaQuanTri"] = admin.MaQuanTri;
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.TrangThai = "Tên tài khoản hoặc mật khẩu không đúng";
                    return View("Index");
                }
            }
            return View("Index");

        }
    }
}

WebDienThoaiDiDong/WebDienThoaiDiDong/Areas/Admin/Views/DangNhapAdmin/Index.cshtml
@using WebDienThoaiDiDong.Models;
@model ADMIN
@{
    Layout = null;
}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Đăng nhập</title>
    <!-- Core CSS - Include with every page -->
    <link href="~/Areas/Admin/Content/assetsLogin/bootstrap/bootstrap.css" rel="stylesheet" />
    <link href="~/Areas/Admin/Content/assetsLogin/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/Areas/Admin/Content/assetsLogin/pace/pace-theme-big-counter.css" rel="stylesheet" />
    <link href="~/Areas/Admin/Content/assetsLogin/css/style.css" rel="stylesheet" />
    <link href="~/Areas/Admin/Content/assetsLogin/css/main-style.css" rel="stylesheet" />

</head>

<body class="body-Login-back">

    <div class="container">

        <div class="row">
            <div class="col-md-4 col-md-offset-4 text-center logo-margin ">
                
            </div>
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">                    
                    <div class="panel-heading">
                        <h3 class="panel-title">Xin mời đăng nhập</h3>
                    </div>
                    <div class="panel-body">
                        @using (Html.BeginForm("DangNhap","DangNhapAdmin",FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true)
                            <fieldset>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Tên đăng nhập" id="username" name="name"  type="text" autofocus>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Mật khẩu" id="password" name="pass" type="password" value="">
                                </div>
                                @Html.ValidationMessageFor(n => n.TenDangNhap)
                                <span style="color:red;">@ViewBag.TrangThai</span> 
                                <div class="checkbox">
                                    <label>
                                        <input name="remember" type="checkbox" value="Remember Me">Nhớ mật khẩu
                                    </label>
                                </div>
                                @Html.ValidationMessageFor(n => n.MatKhau)
                                <!-- Change this to a button or input when using this as a form -->
                                <button type="submit" class="btn btn-lg btn-success btn-block">Đăng nhập</button>
                               
                            </fieldset>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Core Scripts - Include with every page -->
    <script src="~/Areas/Admin/Content/assetsLogin/jquery-1.10.2.js"></script>
    <script src="~/Areas/Admin/Content/assetsLogin/bootstrap/bootstrap.min.js"></script>
    <script src="~/Areas/Admin/Content/assetsLogin/metisMenu/jquery.metisMenu.js"></script>

</body>

</html>